### ISSUE TITLE
Data is lost after flush event is emitted

### ISSUE THREAD

**Issue by kakashif** [tobilg/buffered-queue#1]
I think the buffered queue should create a shallow copy of the items before calling on flush.  Here is my issue.  I am creating the buffered queue with the following configurations for testing without the customResultFunction function:

```
{
    size: 1,
    flushTimeout: 5000,
    verbose: false
}
```

And then on flush, I have:

```
q.on('flush', function(data) {
    // where data[i] => {payload:{}, message: {}};
    myHandler.emit('queue-batch-ready', data);
});
```

I handle the payload part of the array on queue-batch-ready event and then emit another event to handle the message part of the array.  However, by the time I get to processing messages, the data array is empty.

**Comment by tobilg** [comment]
Thanks for submitting the issue. To be honest, I didn't really understand what you're trying to do. Could you either show a little more code, or even issue a pull request?

**Comment by kakashif** [comment]
Sure.  The code I am writing has too many dependencies but here is a dumbed down version of it with test data.

```
var Queue = require('buffered-queue');
var EventEmitter = require('events').EventEmitter;

var emitter = new EventEmitter();
var q = new Queue('test',
    {
        size: 1,
        flushTimeout: 5000,
        verbose: false
    });

emitter.on('do-something', function(flushedData){
   setTimeout(function(){
      //simulate a post to api. expect to do something with flushed data after post completes
       if(flushedData.length === 0){
           throw new Error('why was my data array empty?');
       } else {
           console.log('all good');
       }
   }, 100);
});

q.on('flush', function(data){
    emitter.emit('do-something', data);
});

q.add({key:'value'});
```

**Comment by tobilg** [comment]
I just released a new version on NPM. Please check and close the issue if it works for you. I used your sample code to to test the functionality.

**Comment by kakashif** [comment]
I see your commit. I was going to submit a PR after hearing back from you but you have already done it.  Just FYI, I found a thread on bench marking array shallow copies.  It is worth a look: http://jsperf.com/new-array-vs-splice-vs-slice/113

**Comment by tobilg** [comment]
Thanks, I published a new version with the best-performing method. Version is 0.1.4.

**Comment by enigmatic00** [comment]
The updated version works great. Thanks for the quick turnaround on this.
