### ISSUE TITLE
Force flush queue before shutdown?

### ISSUE THREAD

**Issue by jhecking** [tobilg/buffered-queue#7]
This is more a question than an actual "issue": I'd like to force a flush of the queue when our service gets shut down. Looking at the code, it seems I should be able to use the [`BufferedQueue#onFlush`](https://github.com/tobilg/buffered-queue/blob/3bca3baa8e25237c7d149efe0e329c1ce1752d62/lib/BufferedQueue.js#L122) method to do so. But since this is not really part of the "published" API of the module, I thought I'd better check. Based on the name, I initially thought the `flushItems` method might be what I'm looking for, but that name seems a bit misleading.

Would you be open to a PR to rename `flushItems` -> `clearItems`, rename `onFlush` -> `flushItems`, and then add that function to the modules documentation (aka Readme)?

**Comment by tobilg** [comment]
Hi @jhecking, yes, you can use the `onFlush()` method to actively drain the queue... I think I have to spent some time to refactor this whole library, as its basic implementation is now 6 years old and Node has advanced a lot.
